---
- name: Install apt package lirc
  ansible.builtin.apt:
    pkg:   lirc
    state: latest
  become: true

- name: Deploy lirc remote configuration
  ansible.builtin.copy:
    src:   "{{ item }}"
    dest:  /etc/lirc/lircd.conf.d/
    owner: root
    group: root
    mode:  0655
  become: true
  with_items: "{{ LIRC_BLASTER_REMOTES }}"
  notify: lircd_restart

- name: Disable devinput lirc configuration (dist)
  ansible.builtin.file:
    path:  /etc/lirc/lircd.conf.d/devinput.lircd.conf.dist
    state: absent
  become: true
  notify: lircd_restart

- name: Disable devinput lirc configuration (conf)
  ansible.builtin.file:
    path: /etc/lirc/lircd.conf.d/devinput.lircd.conf
    state: absent
  become: true
  notify: lircd_restart

- name: Deploy lircd.service
  ansible.builtin.template:
    src:   lircd.service
    dest:  /lib/systemd/system/lircd.service
    owner: root
    group: root
    mode:  0655
  become: true
  notify:
    - lircd_restart
    - reboot
    # wtf not sure why but changing device serial number
    # or configuration doesn't work with a service restart
    # alone, so just whack the whole damn thing.
    #
    # Ain't nobody got tiiiime to debug this shit.

- name: Enable lircd service
  ansible.builtin.service:
    name:  lircd
    state: started
  become: true
