---
- name: apt update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr
  become: true

- name: install lirc
  ansible.builtin.import_tasks: lirc.yml

- name: install lirc-web
  ansible.builtin.import_tasks: lirc-web.yml
