---
- name: lircd_restart
  ansible.builtin.service:
    name: lircd
    state: restarted
  become: true

- name: reboot
  ansible.builtin.reboot:
    msg: "Ansible reboot - lircd-blaster role"
  become: true
